### ISSUE TITLE
Adding movies and series plot Hebrew language in a plugin Genesis

### ISSUE THREAD

**Issue by itzikg** [lambda81/lambda-repo#2]
Is it possible to add in a plugin Genesis able to see movies and series plot in Hebrew?

**Comment by itzikg** [comment]
???

**Comment by itzikg** [comment]
???????

**Comment by s7eele** [comment]
hi, im trying to help lambda out with github as he does not have an email registered on github and as I'm sure you already know he spends a massive amount of time coding so there isnt too much leftover for support, unfortunately I'm at a complete disadvantage as I use English (US) for everything so I've never even tried other language options (English is only language), I need some time to get familiar with it but lambda may have the answer already so I will pass this along to him as soon as able and update this issue accordingly, I may have questions as well, for example, I changed language in artwork downloader and got some foreign language artwork and I'm going to try changing the preferred language in metahandler and the scrapers im using to see what that does, if you already know that it won't work and could explain the situation a bit more it would help me

**Comment by s7eele** [comment]
hello again @itzikg 

not sure if it was you but somebody posted a similar question on the forum and lambda was recently able to address there, for your convenience i am going to paste a copy of his response below along with a link to the actual post, if your not already a member take a moment and join us to keep up with all the latest http://forums.tvaddons.ag/register.php?referrerid=3871

following is lambda's response from the thread:

>I've tried it in Genesis 5 and I really really don't like what I have to do. I will have to make 2 calls for >getting them instead of 1 (for each movie). 1 call for getting the metadata for the specific language >and 1 more for getting english metadata in order to add the missing ones. I know that addons that >use metahandler support it, but if you see carefully they are missing a lot of them. This can cause >a lot of problems in Genesis.

and here is a link to the actual thread on the forum:

http://forums.tvaddons.ag/threads/26888-RELEASE-Genesis-addon?p=273267&viewfull=1#post273267

if you find this answer satisfactory please close this issue, if you have further questions or require further explanation please explain

**Comment by lambda81** [comment]
It's been added in 5, so I am closing this issue
